# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3/u4o9S17RzBqB+7Mjni,iv:ETt9vYlJApJb5P8Ov+9ghreki18UiEm89h3Grovl3f0=,tag:eZBEj0KpGqMmmn32lGd9Og==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2usAvTJnbDPGaYV3bETfzKara1M=,iv:F84gyodEq0L7CoNShTsN5oPBMyrDVuX9eqZYa4oIvEY=,tag:59bBoCfTyqbDtVnvEClOXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-20T19:35:51Z"
    mac: ENC[AES256_GCM,data:dLKncs5OJCjj3HRWBqCDZTUCdpDsDV+mus710VjmOOxrlui3N+yg+UuwZ8nPJyYFw+h1Ymbf+cBQVk/YNHL1TAtRJVQukJoZTtaz6OcMtOyxJsbBP9zGRSf9mO9gnokiGL7nT2RqvmIAUn/zYtc7jmaKv/UbVZZJomRvjP0jJlY=,iv:O+BLPyldo0S0l0dW7ruSUwR+y9UnWtmb7bQYqwQ0OoM=,tag:cRaKBoIrMYrIDZJ+ZduODg==,type:str]
    pgp:
        - created_at: "2021-07-20T19:35:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1KSrGeIY9ebAQ/9GeXH/XcEJm2x4VcqF0jlKfVuw8CwAlxLmw5vSJt7dYk3
            Srn6ynr/ybAjDzA+IcyHl9MAoRjYN62Lg4emHhRvrDepJAwXbCa07sE39HcuCuEO
            wDIyKrWm/UO5sfw8J8c3H03YPV9Z4u3Uf0XFfOz3ociME5rLXLm01AA0zHuZG1iV
            ngI5rJDeL6ZvrBcMsbSO67k9IJ8QXaV5aLeS2XlFBn2Q0hse3hmFfAa6Cbtvo7uy
            RN90expbmvaqiDlRyFa7T7b2khFCTcoyZIgH65adwyeAIqXMgmnSr+ISnoD2oAZp
            IIaP9H7LfAZDxlSCi9JOfGwUysEBWR2gdKgMGZGEnldKvcC1lvsKW/Q5zEEg1QFa
            sgms9BFLbta7d6wR3lRt9wfAYQTT9Ub7B2SF9dc0imQzOLGlLbNoeRcXM84x2zY4
            7LnOsBbgqiQksNXC9869gljqAATcLtcbjEK/1uC3HGXIHE+bMV9+3C+GBlaArVKO
            xO9N8tQgVF/mV+oHvSylvBZOi2EsziCbGVQ/zaq/COWAhJaDUTUouTEIqk+g3JTD
            eMG2ZKwSAA3/wWt2Cfh60SbXhKBmtDxJm6pNw8QH98Xlt+Yoht8iH3gPzE7e9b+H
            6fJ1K8RK35AmbKj9IpfNGE7m4GrmcmZS5/sZKWp50DxrevW2mYSc57cDnAF10p/S
            XgGFvltX6GKRz5SsRsoHNtya0Q6PoDaBkgjw9cqbvSkwHZHCNtTrTSZId3diEqCE
            jT4sktILtY/PH2lV1cKuACnUivAtMbUM2tu1YpYmo3ybDRV5t5tSaNsy6J72BjA=
            =1U1o
            -----END PGP MESSAGE-----
          fp: F590460B8617EE146E8E4D06573C755CB6D75DF1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
